config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'home/index'
  resources :bills
  resources :employees
  resources :departments
  resources :designations
  post 'employees/delete_employee/:id', to: "employees#delete_employee"

  root "home#index"
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  belongs_to :designation
  has_many :bills
  validates_presence_of :first_name, :last_name, :email
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  scope :active_employees, -> {(where(is_deleted: false))}
  scope :inactive_employees, -> {(where(is_deleted: true))}


  def department_name
    department.name
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy delete_employee]
  before_action :set_topbar_data
  before_action :set_other_values, only: :edit

  def index
    @employees = Employee.where(is_deleted: false).paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success] = "Employee has been created successfully"
      redirect_to employees_path
    else
      flash[:danger] = "Error." + ' ' + @employee.errors.full_messages.join(", ")
      redirect_to employees_path
    end
  end

  def update
    if @employee.update(employee_params)
      flash[:success] = "Employee has been updated successfully"
      render json: { success: true, flash_message: flash[:success] }
    else
      flash[:danger] = "Error" + ' ' + @employee.errors.full_messages.join(", ")
      render json: { success: false, flash_message: flash.now[:danger] }
    end
  end

  def delete_employee
    if @employee.update(is_deleted: true)
      flash[:success] = "Employee has been deleted successfully"
      redirect_to employees_path
    else
      flash[:danger] = "Error." + ' ' + @employee.errors.full_messages.join(", ")
      redirect_to employees_path
    end
  end

  def destroy
    employee_bill = Bill.where(employee_id: @employee.id).destroy_all
    if @employee.destroy && employee_bill
      employee_bill = Bill.where(employee_id: @employee.id).destroy_all
      flash[:success] = "Employee has been deleted successfully"
      redirect_to employees_path
    else
      flash[:danger] = "Error." + ' ' + @employee.errors.full_messages.join(", ")
      redirect_to employees_path
    end
  end

  private
  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :department_id, :designation_id)
  end

  def set_topbar_data
    @total_bills = Bill.all.count
    amount = 0
    Bill.all.each do |a|
      amount = amount + a.amount
    end
    @total_amount = amount
    @total_employees = Employee.all.count
  end

  def set_other_values
    @departments = Department.all
    @designations = Designation.all
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>First name:</strong>
    <%= employee.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= employee.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= employee.department_id %>
  </p>

  <p>
    <strong>Designation:</strong>
    <%= employee.designation_id %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div style="text-align: left;">
      <%= form.label :first_name, "First Name"  %><span style="color: red;"> *</span>
    </div>
    <%= form.text_field :first_name, class: "form-control", id: "first_name", placeholder: "Enter First Name" %>
  </div>
  <br>

  <div class="form-group">
    <div style="text-align: left;">
      <%= form.label :last_name, "Last Name" %><span style="color: red;"> *</span>
    </div>
    <%= form.text_field :last_name, class: "form-control", id: "last_name", placeholder: "Enter Last Name" %>
  </div>
  <br>

  <div class="form-group">
    <div style="text-align: left;">
      <%= form.label :email %><span style="color: red;"> *</span>
    </div>
    <%= form.text_field :email, class: "form-control", id: "email", placeholder: "Enter E-mail" %>
  </div>
  <br>

  <div class="form-group">
    <div style="text-align: left;">
      <%= form.label :department_id, "Department" %><span style="color: red;"> *</span>
    </div>
    <select class="form-select" id="departmentId" name="employee[department_id]">
      <option value="<%= employee.department_id %>"><%= employee.department.name %></option>
      <% @departments.each do |department| %>
        <% next if department.id == employee.department_id %>
        <option value="<%= department.id %>"><%= department.name %></option>
      <% end %>
    </select>
  </div>
  <br>

  <div class="form-group">
    <div style="text-align: left;">
      <%= form.label :designation_id, "Designation" %><span style="color: red;"> *</span>
    </div>
    <select class="form-select" id="designationId" name="employee[designation_id]">
      <option value="<%= employee.designation_id %>"><%= employee.designation.name %></option>
      <% @designations.each do |designation| %>
        <% next if designation.id == employee.designation_id %>
        <option value="<%= designation.id %>"><%= designation.name %></option>
      <% end %>
    </select>
  </div>
  <br>
  <div class="modal-footer">
    <%= button_tag "Save", class: "btn btn-primary" %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/employees/edit.html.erb
<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<head>
  <style>
    .rounded-table tbody tr:hover {
      background-color: #E6F7FF;
    }
  </style>
   <%= render "common/sidenavbar"%>
   <%= render "common/topbar"%>
</head>
<body style = "background-color: #ededeb;">
  <div class="container-fluid col-8" style="margin-top: 30px; margin-left: 260px; margin-right: auto;">
    <div class="card text-center" style="margin: 0 auto; width: 118%; float: left; border-radius: 10px;">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h5 class="card-title" style="text-align: left;">Employee Details</h5>
        </div>
        <br>
        <table class="table table-striped table-hover rounded-table">
          <h1>
            <thead class="table-light" style="color: black;">
              <tr>
                <th scope="col">Email Address</th>
                <th scope="col">Name</th>
                <th scope="col">Department</th>
                <th scope="col">Designation</th>
                <th scope="col">Edit User</th>
                <th scope="col">Delete User</th>
              </tr>
            </thead>
          </h1>
          <tbody style="color: black;">
            <% @employees.each do |employee|%>
            <tr>
              <td><%= employee.email %></td>
              <td><%= employee.first_name.capitalize +  ' ' + employee.last_name.capitalize%></td>
              <td><%= employee.department.name %></td>
              <td><%= employee.designation.name %></td>
              <td>
                <svg class="edit-button" data-employee-id="<%= employee.id %>" width="24" height="24" viewBox="0 0 24 24" fill="none">
                  <circle cx="12" cy="12" r="12" fill="#DAE2FF"></circle>
                  <g clip-path="url(#clip0_2570_19161)">
                    <path d="M18.1718 8.23582L15.889 5.94137C15.7382 5.79128 15.534 5.70703 15.3213 5.70703C15.1085 5.70703 14.9043 5.79128 14.7535 5.94137L6.6607 14.0225L5.92181 17.2114C5.89632 17.3279 5.8972 17.4487 5.92437 17.5649C5.95154 17.6811 6.00433 17.7898 6.07887 17.8829C6.15341 17.9761 6.24783 18.0515 6.35522 18.1035C6.46261 18.1555 6.58027 18.1829 6.69959 18.1836C6.75519 18.1892 6.81121 18.1892 6.86681 18.1836L10.0907 17.4447L18.1718 9.37137C18.3219 9.22052 18.4062 9.01639 18.4062 8.80359C18.4062 8.5908 18.3219 8.38666 18.1718 8.23582ZM9.70181 16.7447L6.68014 17.3786L7.36848 14.4153L13.4235 8.38359L15.7568 10.7169L9.70181 16.7447ZM16.2779 10.153L13.9446 7.8197L15.2979 6.47415L17.5924 8.80748L16.2779 10.153Z" fill="#2951E2"></path>
                  </g>
                  <defs>
                    <clipPath id="clip0_2570_19161">
                      <rect width="14" height="14" fill="white" transform="translate(5 5)"></rect>
                    </clipPath>
                  </defs>
                </svg>
              </td>
              <td>
                <a href="#" onclick="deleteEmployee('<%= employee.id %>'); return false;">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="12" fill="#FFD1D1"></circle><path d="M8.50033 16.0833C8.50033 16.725 9.02533 17.25 9.66699 17.25H14.3337C14.9753 17.25 15.5003 16.725 15.5003 16.0833V9.08333H8.50033V16.0833ZM9.66699 10.25H14.3337V16.0833H9.66699V10.25ZM14.042 7.33333L13.4587 6.75H10.542L9.95866 7.33333H7.91699V8.5H16.0837V7.33333H14.042Z" fill="#ED3B41"></path></svg>
                </a>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="pagination">
          <%= will_paginate @bills, outer_window: 1, inner_window: 2, previous_label: '&laquo; Previous', next_label: 'Next &raquo;', class: 'pagination-links' %>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'shared/editemployee' %>
</body>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const editButtons = document.querySelectorAll('.edit-button');

    editButtons.forEach(function(editButton) {
      editButton.addEventListener('click', function() {
        const employeeId = this.dataset.employeeId;
        const modalBody = document.querySelector('#editEmployeesModal .modal-body');
        const xhr = new XMLHttpRequest();
        xhr.open('GET', '/employees/' + employeeId + '/edit');
        xhr.onload = function() {
          if (xhr.status === 200) {
            const modalBody = document.querySelector('#editEmployeesModal .modal-body');
            modalBody.innerHTML = xhr.responseText;
            const form = modalBody.querySelector('form');
            form.addEventListener('submit', function(event) {
              event.preventDefault();
              const formData = new FormData(form);
              const xhr = new XMLHttpRequest();
              xhr.open('PATCH', '/employees/' + employeeId);
              xhr.setRequestHeader('Accept', 'application/json');
              xhr.onload = function() {
                if (xhr.status === 200) {
                  const response = JSON.parse(xhr.responseText);
                  if (response.success) {
                    $('#editEmployeesModal').modal('hide');
                    location.reload();
                  } else {
                    const errorDiv = form.querySelector('.errors');
                    errorDiv.innerHTML = response.errors.join(', ');
                  }
                } else {
                  console.error('Request failed. Status: ' + xhr.status);
                }
              };
              xhr.send(formData);
            });
            $('#editEmployeesModal').modal('show');
          } else {
            console.error('Request failed. Status: ' + xhr.status);
          }
        };
        xhr.send();
      });
    });
  });

  function deleteEmployee(employeeId) {
    const csrfToken = document.querySelector('meta[name="csrf-token"]').content;
    fetch(`/employees/delete_employee/${employeeId}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': '<%= form_authenticity_token %>'
      }
    })
    .then(response => {
      if (response.ok) {
        console.log('Employee deleted successfully');
      } else {
        console.error('Error deleting the Employee:', response.status);
      }
      location.reload();
    })
    .catch(error => {
      console.error('Error deleting the Employee:', error);
    });
  }
</script>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>