config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'home/index'
  resources :bills
  resources :employees
  resources :departments
  resources :designations
  post 'employees/delete_employee/:id', to: "employees#delete_employee"

  root "home#index"
end

app/models/designation.rb
class Designation < ApplicationRecord
  has_many :employees
  validates_uniqueness_of :name, case_sensitive: false
  validates_presence_of :name
end

app/controllers/designations_controller.rb
class DesignationsController < ApplicationController
  before_action :set_designation, only: %i[ show edit update destroy ]
  before_action :set_topbar_data

  def index
    @designations = Designation.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @designation = Designation.new
  end

  def edit
  end

  def create
    @designation = Designation.new(designation_params)
    if @designation.save
      flash[:success] = "Designation created successfully"
    else
      flash[:danger] = "Error." + ' ' + @designation.errors.full_messages.join(", ")
    end
  end

  def update
    if @designation.update(designation_params)
      flash[:success] = "Designation updated successfully"
      render json: { success: true, flash_message: flash[:success] }
    else
      flash[:danger] = "Error." + ' ' + @designation.errors.full_messages.join(", ")
      render json: { success: false, flash_message: flash.now[:danger] }
    end
  end

  def destroy
    employee_count = @designation.employees.count
    if employee_count.zero? && @designation.destroy
      flash[:success] = "Designation deleted successfully"
      redirect_to designations_path
    else
      flash[:danger] = "Cannot delete Designation. There are #{employee_count} employees associated with it."
      redirect_to designations_path
    end
  end

  private
  def set_designation
    p params[:id]
    @designation = Designation.find(params[:id])
  end

  def designation_params
    params.require(:designation).permit(:name)
  end

  def set_topbar_data
    @total_bills = Bill.all.count
    amount = 0
    Bill.all.each do |a|
      amount = amount + a.amount
    end
    @total_amount = amount
    @total_employees = Employee.all.count
  end
end

app/helpers/designations_helper.rb
module DesignationsHelper
end

app/views/designations/_designation.html.erb
<div id="<%= dom_id designation %>">
  <p>
    <strong>Name:</strong>
    <%= designation.name %>
  </p>

</div>

app/views/designations/_form.html.erb
<%= form_with(model: designation) do |form| %>
  <% if designation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(designation.errors.count, "error") %> prohibited this designation from being saved:</h2>

      <ul>
        <% designation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div style="text-align: left;">
      <%= form.label :name, "Name of Designation" %><span style="color: red;"> *</span>
    </div>
    <%= form.text_field :name, class: "form-control", id: "name", placeholder: "Enter Designation Name" %>
  </div>
  <br>
  <div class="modal-footer">
    <%= button_tag "Save", class: "btn btn-primary" %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/designations/edit.html.erb
<%= render "form", designation: @designation %>

app/views/designations/index.html.erb
<head>
  <style>
    .rounded-table tbody tr:hover {
      background-color: #E6F7FF;
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
   <%= render "common/sidenavbar"%>
   <%= render "common/topbar"%>
</head>
<body style = "background-color: #ededeb;">
  <div class="container-fluid col-8" style="margin-top: 30px; margin-left: 260px; margin-right: auto;">
    <div class="card text-center" style="margin: 0 auto; width: 118%; float: left; border-radius: 10px;">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h3 class="card-title" style="text-align: left;">Designations</h3>
        </div>
        <br>
        <table class="table table-striped table-hover rounded-table">
          <h1>
              <thead class="table-light" style="color: black;">
                <tr>
                  <th scope="col">Designation Name</th>
                  <th scope="col">Edit</th>
                  <th scope="col">Delete</th>
                </tr>
              </thead>
            <h1>
          <tbody style="color: black;">
            <% @designations.each do |designation|%>
            <tr>
              <td><%= designation.name %></td>
              <td>
                <svg class="edit-button" data-designation-id="<%= designation.id %>" width="24" height="24" viewBox="0 0 24 24" fill="none">
                  <circle cx="12" cy="12" r="12" fill="#DAE2FF"></circle>
                  <g clip-path="url(#clip0_2570_19161)">
                    <path d="M18.1718 8.23582L15.889 5.94137C15.7382 5.79128 15.534 5.70703 15.3213 5.70703C15.1085 5.70703 14.9043 5.79128 14.7535 5.94137L6.6607 14.0225L5.92181 17.2114C5.89632 17.3279 5.8972 17.4487 5.92437 17.5649C5.95154 17.6811 6.00433 17.7898 6.07887 17.8829C6.15341 17.9761 6.24783 18.0515 6.35522 18.1035C6.46261 18.1555 6.58027 18.1829 6.69959 18.1836C6.75519 18.1892 6.81121 18.1892 6.86681 18.1836L10.0907 17.4447L18.1718 9.37137C18.3219 9.22052 18.4062 9.01639 18.4062 8.80359C18.4062 8.5908 18.3219 8.38666 18.1718 8.23582ZM9.70181 16.7447L6.68014 17.3786L7.36848 14.4153L13.4235 8.38359L15.7568 10.7169L9.70181 16.7447ZM16.2779 10.153L13.9446 7.8197L15.2979 6.47415L17.5924 8.80748L16.2779 10.153Z" fill="#2951E2"></path>
                  </g>
                  <defs>
                    <clipPath id="clip0_2570_19161">
                      <rect width="14" height="14" fill="white" transform="translate(5 5)"></rect>
                    </clipPath>
                  </defs>
                </svg>
              </td>
              <td>
                <a href="#" onclick="deleteDesignation('<%= designation.id %>'); return false;">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="12" fill="#FFD1D1"></circle><path d="M8.50033 16.0833C8.50033 16.725 9.02533 17.25 9.66699 17.25H14.3337C14.9753 17.25 15.5003 16.725 15.5003 16.0833V9.08333H8.50033V16.0833ZM9.66699 10.25H14.3337V16.0833H9.66699V10.25ZM14.042 7.33333L13.4587 6.75H10.542L9.95866 7.33333H7.91699V8.5H16.0837V7.33333H14.042Z" fill="#ED3B41"></path></svg>
                </a>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="pagination">
          <%= will_paginate @bills, outer_window: 1, inner_window: 2, previous_label: '&laquo; Previous', next_label: 'Next &raquo;', class: 'pagination-links' %>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'shared/editdesignation' %>
</body>

<script>
    document.addEventListener('DOMContentLoaded', function() {
    const editButtons = document.querySelectorAll('.edit-button');

    editButtons.forEach(function(editButton) {
      editButton.addEventListener('click', function() {
        const designationId = this.dataset.designationId;
        const modalBody = document.querySelector('#editDesignationsModal .modal-body');

        const xhr = new XMLHttpRequest();
        xhr.open('GET', '/designations/' + designationId + '/edit');
        xhr.onload = function() {
          if (xhr.status === 200) {
            const modalBody = document.querySelector('#editDesignationsModal .modal-body');
            modalBody.innerHTML = xhr.responseText;
            const form = modalBody.querySelector('form');
            form.addEventListener('submit', function(event) {
              event.preventDefault();
              const formData = new FormData(form);
              const xhr = new XMLHttpRequest();
              xhr.open('PATCH', '/designations/' + designationId);
              xhr.setRequestHeader('Accept', 'application/json');
              xhr.onload = function() {
                if (xhr.status === 200) {
                  const response = JSON.parse(xhr.responseText);
                  if (response.success) {
                    $('#editDesignationsModal').modal('hide');
                    location.reload();
                  } else {
                    const errorDiv = form.querySelector('.errors');
                    errorDiv.innerHTML = response.errors.join(', ');
                  }
                } else {
                  console.error('Request failed. Status: ' + xhr.status);
                }
              };
              xhr.send(formData);
            });
            $('#editDesignationsModal').modal('show');
          } else {
            console.error('Request failed. Status: ' + xhr.status);
          }
        };
        xhr.send();
      });
    });
  });

  function deleteDesignation(designationId) {
    const csrfToken = document.querySelector('meta[name="csrf-token"]').content;
    fetch(`/designations/${designationId}`, {
      method: 'DELETE',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': '<%= form_authenticity_token %>'
      }
    })
    .then(response => {
      if (response.ok) {
        console.log('Designation deleted successfully');
      } else {
        console.error('Error deleting the designation:', response.status);
      }
      location.reload();
    })
    .catch(error => {
      console.error('Error deleting the designation:', error);
    });
  }
</script>

app/views/designations/new.html.erb
<h1>New designation</h1>

<%= render "form", designation: @designation %>

<br>

<div>
  <%= link_to "Back to designations", designations_path %>
</div>

app/views/designations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @designation %>

<div>
  <%= link_to "Edit this designation", edit_designation_path(@designation) %> |
  <%= link_to "Back to designations", designations_path %>

  <%= button_to "Destroy this designation", @designation, method: :delete %>
</div>