config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'home/index'
  resources :bills
  resources :employees
  resources :departments
  resources :designations
  post 'employees/delete_employee/:id', to: "employees#delete_employee"

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_topbar_data

  def index
    @bills = Bill.order(created_at: :desc).limit(5)
    @departments = Department.all
    @designations = Designation.all
    @employees = Employee.all
  end

  private
  
  def set_topbar_data
    @total_bills = Bill.all.count
    amount = 0
    Bill.all.each do |a|
      amount = amount + a.amount
    end
    @total_amount = amount
    @total_employees = Employee.all.count
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap.min.css">
  <style>
    .rounded-table tbody tr:hover {
      background-color: #E6F7FF;
    }
  </style>
   <%= render "common/sidenavbar"%>
   <%= render "common/topbar"%>
</head>
<body style = "background-color: #ededeb;">
  <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox float-e-margins">
          <div class="ibox-content">
            <% flash.each do |k, v| %>
              <% if k == "alert" %>
                <div class="alert alert-danger alert-dismissable">
                  <button class="close" aria-hidden="true" data-dismiss="alert" type="button" x></button>
                  <%= v %>.
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card-container">
    <div class="card-button" style="margin-left: 270px; margin-top: -10px; width: 265px; background-color: #e2eef6;">
      <button id="addEmployeesButton" type="button" class="btn btn-secondary btn-lg" style="color: black; data-form-url="<%= new_employee_path %>">Add Employees</button>
    </div>
    <div class="card-button" style="margin-left: 10px; margin-top: 20px; width: 265px; background-color: #e2eef6;">
      <button id="addDepartmentButton" type="button" class="btn btn-secondary btn-lg" style="color: black; data-form-url="<%= new_department_path %>">Add Department</button>
    </div>
    <div class="card-button" style="margin-left: 10px; margin-top: -10px; width: 265px; background-color: #e2eef6;">
      <button id="addDesignationButton" type="button" class="btn btn-secondary btn-lg" style="color: black; data-form-url="<%= new_designation_path %>">Add Designation</button>
    </div>
    <div class="card-button" style="margin-left: 10px; margin-top: -10px; width: 265px; background-color: #e2eef6;">
      <button id="addBillsButton" type="button" class="btn btn-secondary btn-lg" style="color: black; data-form-url="<%= new_bill_path %>">Add Bills</button>
    </div>
  </div>
  <div class="container-fluid col-8" style="margin-top: 30px; margin-left: 260px; margin-right: auto;">
    <div class="card text-center" style="margin: 0 auto; width: 118%; float: left; border-radius: 10px;">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h3 class="card-title" style="color: black; text-align: left;">Recent Bills</h3>
          <button class="btn btn-secondary btn-sm" onclick="location.href='<%= bills_path %>'">View All</button>
        </div>
        <br>
          <table class="table table-striped table-hover rounded-table">
          <thead class="table-light">
          <h1>
            <tr style="color: black;">
              <th scope="col">S.No</th>
              <th scope="col">Type</th>
              <th scope="col">Amount</th>
              <th scope="col">Date of Submission</th>
              <th scope="col">Submitted By</th>
            </tr>
          </h1>
          </thead>
          <tbody style="color: black;">
            <% c=0 %>
            <% @bills.each do |bill|%>
            <tr>
              <% c+=1 %>
              <th scope="row"><%= c %></th>
              <td><%= bill.bill_type.capitalize %></td>
              <td><%= bill.amount %></td>
              <td><%= bill.created_at.to_date.strftime('%d-%m-%Y') %></td>
              <td><%= bill.employee.first_name + ' '  + bill.employee.last_name %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/js/bootstrap.bundle.min.js"></script>

  <%= render partial: 'shared/employee' %>
  <%= render partial: 'shared/department' %>
  <%= render partial: 'shared/designation' %>
  <%= render partial: 'shared/bill' %>
</body>
</html>